version: "3.0"

services:
  app:
    build:
      dockerfile: ./.docker/app/Dockerfile
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - ./src:/app
    networks:
      - bridge
